<%
requires = "--require features/support --require features/step_definitions"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} --strict --tags ~@wip #{requires}"
%>
default: <%= std_opts %> features
wip: --tags @wip:3 --wip <%= requires %> features
